var searchData=
[
  ['parámetros_0',['Tabla Completa de Parámetros',['../index.html#autotoc_md37',1,'']]],
  ['parámetros_20clave_1',['Parámetros Clave',['../index.html#autotoc_md24',1,'Parámetros Clave'],['../index.html#autotoc_md32',1,'Parámetros Clave']]],
  ['parámetros_20configurables_2',['Parámetros Configurables',['../index.html#autotoc_md36',1,'']]],
  ['path_5fpoints_5f_3',['path_points_',['../class_pure_pursuit_node.html#af6298f8e3dd0f36e961cd96c8e1507ab',1,'PurePursuitNode']]],
  ['path_5fpub_5f_4',['path_pub_',['../class_route_publisher.html#ac8efa1709b996f8bb4955318183b6f8e',1,'RoutePublisher']]],
  ['path_5fsub_5f_5',['path_sub_',['../class_pure_pursuit_node.html#ade017bfbffe7f38dde72ed9df49a2469',1,'PurePursuitNode']]],
  ['pathcallback_6',['pathCallback',['../class_pure_pursuit_node.html#abea4d2512c764e21c1b10270469c6621',1,'PurePursuitNode']]],
  ['planificador_7',['A. Nodo Publicador de Rutas (Planificador)',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md65',1,'']]],
  ['planificador_20de_20trayectorias_8',['A. Route Publisher (Planificador de Trayectorias)',['../index.html#autotoc_md21',1,'']]],
  ['por_20pure_20pursuit_20node_9',['por Pure Pursuit Node',['../index.html#autotoc_md46',1,'Topics Publicados por Pure Pursuit Node'],['../index.html#autotoc_md47',1,'Topics Suscritos por Pure Pursuit Node']]],
  ['por_20route_20publisher_10',['por Route Publisher',['../index.html#autotoc_md44',1,'Topics Publicados por Route Publisher'],['../index.html#autotoc_md45',1,'Topics Suscritos por Route Publisher']]],
  ['principales_11',['Principales',['../index.html#autotoc_md22',1,'Funcionalidades Principales'],['../index.html#autotoc_md29',1,'Funcionalidades Principales']]],
  ['principio_20de_20funcionamiento_12',['Principio de Funcionamiento',['../index.html#autotoc_md13',1,'']]],
  ['publicador_20de_20rutas_20planificador_13',['A. Nodo Publicador de Rutas (Planificador)',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md65',1,'']]],
  ['publicados_14',['Publicados',['../index.html#autotoc_md25',1,'Topics Publicados'],['../index.html#autotoc_md33',1,'Topics Publicados']]],
  ['publicados_20por_20pure_20pursuit_20node_15',['Topics Publicados por Pure Pursuit Node',['../index.html#autotoc_md46',1,'']]],
  ['publicados_20por_20route_20publisher_16',['Topics Publicados por Route Publisher',['../index.html#autotoc_md44',1,'']]],
  ['publishbubbleviz_17',['publishBubbleViz',['../class_pure_pursuit_node.html#a86396b82599e631edeadbe37b335cab0',1,'PurePursuitNode']]],
  ['publishcurrentwaypoint_18',['publishCurrentWaypoint',['../class_route_publisher.html#ad3df8c74e6e5d832ac6da67dddde7856',1,'RoutePublisher']]],
  ['publishdetourpath_19',['publishDetourPath',['../class_pure_pursuit_node.html#ab5dc33aa724510df1f5fbabf7e88d4b2',1,'PurePursuitNode']]],
  ['publisher_20',['Publisher',['../index.html#autotoc_md38',1,'Route Publisher'],['../index.html#autotoc_md44',1,'Topics Publicados por Route Publisher'],['../index.html#autotoc_md45',1,'Topics Suscritos por Route Publisher']]],
  ['publisher_20planificador_20de_20trayectorias_21',['A. Route Publisher (Planificador de Trayectorias)',['../index.html#autotoc_md21',1,'']]],
  ['publishlookaheadmarker_22',['publishLookaheadMarker',['../class_pure_pursuit_node.html#afd5b20e7bf87bb3f8e86af080008fe05',1,'PurePursuitNode']]],
  ['publishrobotmarker_23',['publishRobotMarker',['../class_pure_pursuit_node.html#ac983fdab68d008d317db5666cc83ea37',1,'PurePursuitNode']]],
  ['publishstatictf_24',['publishStaticTF',['../class_route_publisher.html#a62bfe6239ef9e150d053c4ab1e0e2369',1,'RoutePublisher']]],
  ['publishwaypointsmarkers_25',['publishWaypointsMarkers',['../class_route_publisher.html#adf0a9a4daeb8818cccdfe960978cf9f5',1,'RoutePublisher']]],
  ['publishwaypointspath_26',['publishWaypointsPath',['../class_route_publisher.html#ad2e56de58e5f2ae4e04b55aebdb169ef',1,'RoutePublisher']]],
  ['pure_20pursuit_27',['Pure Pursuit',['../index.html#autotoc_md12',1,'Algoritmo Pure Pursuit'],['../index.html#autotoc_md1',1,'CPR-ROSbot2-Pure-Pursuit'],['../index.html',1,'Sistema de Navegación Autónoma con Pure Pursuit']]],
  ['pure_20pursuit_20evasión_28',['B. Nodo Controlador (Pure Pursuit + Evasión)',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md66',1,'']]],
  ['pure_20pursuit_20node_29',['Pure Pursuit Node',['../index.html#autotoc_md39',1,'Pure Pursuit Node'],['../index.html#autotoc_md46',1,'Topics Publicados por Pure Pursuit Node'],['../index.html#autotoc_md47',1,'Topics Suscritos por Pure Pursuit Node']]],
  ['pure_20pursuit_20node_20controlador_20de_20seguimiento_30',['B. Pure Pursuit Node (Controlador de Seguimiento)',['../index.html#autotoc_md28',1,'']]],
  ['pure_5fpursuit_31',['pure_pursuit',['../namespacepure__pursuit.html',1,'']]],
  ['pure_5fpursuit_2elaunch_2epy_32',['pure_pursuit.launch.py',['../pure__pursuit_8launch_8py.html',1,'']]],
  ['pure_5fpursuit_5fnode_2ecpp_33',['pure_pursuit_node.cpp',['../pure__pursuit__node_8cpp.html',1,'']]],
  ['purepursuitnode_34',['PurePursuitNode',['../class_pure_pursuit_node.html',1,'PurePursuitNode'],['../class_pure_pursuit_node.html#a632632d700de02398bcf186016149b51',1,'PurePursuitNode::PurePursuitNode()']]],
  ['pursuit_35',['Pursuit',['../index.html#autotoc_md12',1,'Algoritmo Pure Pursuit'],['../index.html#autotoc_md1',1,'CPR-ROSbot2-Pure-Pursuit'],['../index.html',1,'Sistema de Navegación Autónoma con Pure Pursuit']]],
  ['pursuit_20evasión_36',['B. Nodo Controlador (Pure Pursuit + Evasión)',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md66',1,'']]],
  ['pursuit_20node_37',['Pursuit Node',['../index.html#autotoc_md39',1,'Pure Pursuit Node'],['../index.html#autotoc_md46',1,'Topics Publicados por Pure Pursuit Node'],['../index.html#autotoc_md47',1,'Topics Suscritos por Pure Pursuit Node']]],
  ['pursuit_20node_20controlador_20de_20seguimiento_38',['B. Pure Pursuit Node (Controlador de Seguimiento)',['../index.html#autotoc_md28',1,'']]]
];
