var searchData=
[
  ['data_5flog_5ffile_5f_0',['data_log_file_',['../class_pure_pursuit_node.html#a6fed0551075c64e145a7436a3142d945',1,'PurePursuitNode']]],
  ['de_20bézier_1',['Generación de Desvíos (Curvas de Bézier)',['../index.html#autotoc_md31',1,'']]],
  ['de_20desvíos_20curvas_20de_20bézier_2',['Generación de Desvíos (Curvas de Bézier)',['../index.html#autotoc_md31',1,'']]],
  ['de_20detección_3',['Algoritmo de Detección',['../index.html#autotoc_md52',1,'']]],
  ['de_20estados_4',['de Estados',['../index.html#autotoc_md30',1,'Máquina de Estados'],['../index.html#autotoc_md53',1,'Visualización de Estados']]],
  ['de_20evasión_20de_20obstáculos_5',['Sistema de Evasión de Obstáculos',['../index.html#autotoc_md49',1,'']]],
  ['de_20funcionamiento_6',['de Funcionamiento',['../index.html#autotoc_md9',1,'Flujo de Funcionamiento'],['../index.html#autotoc_md13',1,'Principio de Funcionamiento']]],
  ['de_20logging_7',['Sistema de Logging',['../index.html#autotoc_md55',1,'']]],
  ['de_20los_20módulos_8',['3. Descripción de los Módulos',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md64',1,'']]],
  ['de_20navegación_20autónoma_20con_20pure_20pursuit_9',['Sistema de Navegación Autónoma con Pure Pursuit',['../index.html',1,'']]],
  ['de_20nodos_10',['Diagrama de Nodos',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md62',1,'']]],
  ['de_20obstáculos_11',['Sistema de Evasión de Obstáculos',['../index.html#autotoc_md49',1,'']]],
  ['de_20parámetros_12',['Tabla Completa de Parámetros',['../index.html#autotoc_md37',1,'']]],
  ['de_20rutas_20planificador_13',['A. Nodo Publicador de Rutas (Planificador)',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md65',1,'']]],
  ['de_20seguimiento_14',['B. Pure Pursuit Node (Controlador de Seguimiento)',['../index.html#autotoc_md28',1,'']]],
  ['de_20seguridad_15',['Burbuja de Seguridad',['../index.html#autotoc_md51',1,'']]],
  ['de_20topics_16',['de Topics',['../index.html#autotoc_md42',1,'Diagrama de Topics'],['../index.html#autotoc_md43',1,'Referencia Completa de Topics']]],
  ['de_20trayectorias_17',['A. Route Publisher (Planificador de Trayectorias)',['../index.html#autotoc_md21',1,'']]],
  ['defineroute_18',['defineRoute',['../class_route_publisher.html#acb10d8636504050556a64954aefb7ffb',1,'RoutePublisher']]],
  ['del_20sistema_19',['del Sistema',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md61',1,'2. Arquitectura del Sistema'],['../index.html#autotoc_md8',1,'Arquitectura del Sistema'],['../index.html#autotoc_md50',1,'Funcionamiento del Sistema'],['../index.html#autotoc_md20',1,'Módulos del Sistema']]],
  ['delta_5fmax_5f_20',['delta_max_',['../class_pure_pursuit_node.html#ae8800c239fda5ae33481d8c72cb3996c',1,'PurePursuitNode']]],
  ['delta_5fmin_5f_21',['delta_min_',['../class_pure_pursuit_node.html#abae562d7eb93b45c29de9ef09565897b',1,'PurePursuitNode']]],
  ['descripción_20de_20los_20módulos_22',['3. Descripción de los Módulos',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md64',1,'']]],
  ['destacadas_23',['Características Destacadas',['../index.html#autotoc_md6',1,'']]],
  ['desvíos_20curvas_20de_20bézier_24',['Generación de Desvíos (Curvas de Bézier)',['../index.html#autotoc_md31',1,'']]],
  ['detección_25',['Algoritmo de Detección',['../index.html#autotoc_md52',1,'']]],
  ['detour_5foffset_5f_26',['detour_offset_',['../class_pure_pursuit_node.html#ad5769e2edb221ac3205199160a8165d4',1,'PurePursuitNode']]],
  ['detour_5fpath_5fpub_5f_27',['detour_path_pub_',['../class_pure_pursuit_node.html#a126cf53791816015aba5dc33ff397352',1,'PurePursuitNode']]],
  ['diagrama_20de_20nodos_28',['Diagrama de Nodos',['../C:/Users/Almudena/OneDrive/Escritorio/CPR_proyecto/CPR-ROSbot2-Pure-Pursuit/pure_pursuit_controller/docs/mainpage_antes.md#autotoc_md62',1,'']]],
  ['diagrama_20de_20topics_29',['Diagrama de Topics',['../index.html#autotoc_md42',1,'']]],
  ['disponibles_30',['Rutas Disponibles',['../index.html#autotoc_md23',1,'']]]
];
